name: wa_sticker_maker
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.1+1
environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.4.0
  loading_animation_widget: ^1.3.0
  gap: ^3.0.1
  path_provider: ^2.1.5
  shared_preferences: ^2.5.3
  toastification: ^3.0.3
  shimmer: ^3.0.0
  slide_to_act: ^2.0.2
  flutter_riverpod: ^3.0.0
  url_launcher: ^6.3.1
  lottie:
  carousel_slider: ^5.1.1
  image_picker: ^1.2.0
  pro_image_editor:
  permission_handler: ^12.0.1
  whatsapp_stickers_handler: ^0.5.0
  connectivity_plus: ^7.0.0
  get: ^4.7.2
  image: ^4.5.4
  flutter_image_compress: ^2.4.0
  firebase_core: ^3.14.0
  firebase_remote_config: ^5.4.5
  firebase_analytics:
  firebase_crashlytics:
  onesignal_flutter: ^5.3.4
  google_mobile_ads: ^6.0.0
  flutter_launcher_icons: "^0.14.4"
  in_app_purchase: ^3.2.0
  in_app_purchase_android: ^0.4.0
  cached_network_image: ^3.4.1
  photo_view: ^0.15.0

flutter_launcher_icons:
    android: true
    ios: true
    image_path: "images/2x/icon.png"
    min_sdk_android: 24
    remove_alpha_ios: true

dependency_overrides:
  whatsapp_stickers_handler:
    path: plugins/whatsapp_stickers_handler-main

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - images/
    - assets/animations/
    - assets/sticker_packs/01_Funny/
    - assets/sticker_packs/02_Football/
    - assets/sticker_packs/03_Emotions/
    - assets/sticker_packs/04_Basketball/
    - assets/sticker_packs/05_Head/
    - assets/sticker_packs/06_Korean Guy/
    - assets/sticker_packs/07_Pewdiepie/
    - assets/sticker_packs/08_Stick Man/
    - assets/sticker_packs/09_Snowden/
    - assets/sticker_packs/10_Spongebob/
    - assets/sticker_packs/11_Tom And Jerry/
    - assets/sticker_packs/12_Toy Story/
    - assets/sticker_packs/13_Courage/
    - assets/sticker_packs/14_Cat/
    - assets/sticker_packs/15_Agent 007/
    - assets/sticker_packs/16_Black Cat/
    - assets/sticker_packs/17_Ghost/
